import { OASDIFF_VERSION } from '../oasdiff/version.js';
import { VersionError } from './errors.js';
import { readJsonFile } from './json-file.js';
import { coveredKeywordsFileSchema } from './types.js';

export interface LoadCoveredKeywordsOptions {
  /** Overridden only in tests; defaults to the oasdiff version Speckify is pinned to. */
  expectedOasdiffVersion?: string;
}

/**
 * Loads and validates the committed covered-keywords file
 * (`data/oasdiff-<version>.covered-keywords.json`): every JSON-Schema/
 * OpenAPI keyword oasdiff's own rule catalogue ever judges at all,
 * generated by `scripts/generate-oasdiff-covered-keywords.mjs` from the
 * same rule catalogue `classification-map.ts` loads.
 *
 * `plan.ts`'s structural fallback uses this the other way round from the
 * classification map: a real structural difference at a keyword *absent*
 * from this set is one oasdiff has no rule for at all, so oasdiff's silence
 * about it carries no information -- Speckify forces major rather than
 * trust it.
 *
 * @throws {VersionError} if the file cannot be read or parsed, fails
 * schema validation, or is pinned to a different oasdiff version than
 * Speckify's own {@link OASDIFF_VERSION}.
 */
export async function loadCoveredKeywords(
  filePath: string,
  options: LoadCoveredKeywordsOptions = {},
): Promise<ReadonlySet<string>> {
  const expectedOasdiffVersion = options.expectedOasdiffVersion ?? OASDIFF_VERSION;

  const raw = await readJsonFile(filePath);
  const result = coveredKeywordsFileSchema.safeParse(raw);
  if (!result.success) {
    throw new VersionError(
      `${filePath} is not a valid covered-keywords file: ${result.error.message}`,
    );
  }
  const file = result.data;

  if (file.oasdiffVersion !== expectedOasdiffVersion) {
    throw new VersionError(
      `${filePath} is pinned to oasdiff ${file.oasdiffVersion}, but Speckify is pinned to ${expectedOasdiffVersion}; regenerate the covered-keywords file (scripts/generate-oasdiff-covered-keywords.mjs) before upgrading oasdiff`,
    );
  }

  return new Set(file.keywords);
}
