import { toCamelCase, toPascalCase } from '../naming.js';
import type { OperationInfo } from '../operations.js';

const HEADER = '// Generated by Speckify. Do not edit by hand.\n';

function bodyMode(op: OperationInfo): 'json' | 'octet-stream' | 'none' {
  if (op.isOctetStreamBody) return 'octet-stream';
  if (op.hasRequestBody) return 'json';
  return 'none';
}

/**
 * Generates `routes.gen.ts`: the runtime route table the server adapter
 * dispatches on. Each entry references the zod validators hey-api's zod
 * plugin already emitted for that operation, by the name that plugin's
 * naming convention guarantees.
 */
export function generateRoutesSource(operations: readonly OperationInfo[]): string {
  const zodImports = new Set<string>();
  const entries: string[] = [];

  for (const op of operations) {
    const pascal = toPascalCase(op.operationId);
    const camel = toCamelCase(op.operationId);
    const fields = [
      `    id: '${camel}'`,
      `    method: '${op.method.toUpperCase()}'`,
      `    path: '${op.path}'`,
      `    bodyMode: '${bodyMode(op)}'`,
    ];

    if (op.hasPathParams) {
      zodImports.add(`z${pascal}Path`);
      fields.push(`    pathSchema: z${pascal}Path`);
    }
    if (op.hasQueryParams) {
      zodImports.add(`z${pascal}Query`);
      fields.push(`    querySchema: z${pascal}Query`);
    }
    if (op.hasHeaderParams) {
      zodImports.add(`z${pascal}Headers`);
      fields.push(`    headersSchema: z${pascal}Headers`);
    }
    if (op.hasRequestBody && !op.isOctetStreamBody) {
      zodImports.add(`z${pascal}Body`);
      fields.push(`    bodySchema: z${pascal}Body`);
    }
    if (op.successStatus !== undefined) {
      zodImports.add(`z${pascal}Response`);
      fields.push(`    responseSchemas: { ${op.successStatus.toString()}: z${pascal}Response }`);
    }

    entries.push(`  {\n${fields.join(',\n')},\n  }`);
  }

  const zodImportLine =
    zodImports.size > 0
      ? `import { ${[...zodImports].sort().join(', ')} } from './zod.gen.js';\n`
      : '';

  return (
    HEADER +
    "import type { RouteDefinition } from './server-adapter.js';\n" +
    zodImportLine +
    '\n' +
    `export const routes: RouteDefinition[] = [\n${entries.join(',\n')},\n];\n`
  );
}
