import { toCamelCase, toPascalCase } from '../naming.js';
import type { OperationInfo } from '../operations.js';

const HEADER = '// Generated by Speckify. Do not edit by hand.\n';

function requestTypeExpression(
  op: OperationInfo,
  pascal: string,
): {
  path: string;
  query: string;
  headers: string;
  body: string;
} {
  const path = op.hasPathParams ? `${pascal}Data['path']` : 'undefined';
  const query = op.hasQueryParams ? `${pascal}Data['query']` : 'undefined';
  const headers = op.hasHeaderParams ? `${pascal}Data['headers']` : 'undefined';
  const body = op.isOctetStreamBody
    ? 'Readable'
    : op.hasRequestBody
      ? `${pascal}Data['body']`
      : 'undefined';
  return { path, query, headers, body };
}

/**
 * Generates `handlers.gen.ts`: one `Handlers` method per operationId, typed
 * against hey-api's own `{Pascal}Data`/`{Pascal}Responses` types so the
 * request/response shapes are never re-invented. `HandlerRequest` and
 * `HandlerResponse` are the two generics the server-adapter template
 * defines once and reuses for every operation.
 */
export function generateHandlersSource(operations: readonly OperationInfo[]): string {
  const dataTypeNames = new Set<string>();
  const responseTypeNames = new Set<string>();
  const methods: string[] = [];
  const needsReadable = operations.some((op) => op.isOctetStreamBody);

  for (const op of operations) {
    const pascal = toPascalCase(op.operationId);
    const camel = toCamelCase(op.operationId);
    dataTypeNames.add(`${pascal}Data`);
    responseTypeNames.add(`${pascal}Responses`);
    let responsesExpr = `${pascal}Responses`;
    if (op.hasDocumentedErrors) {
      responseTypeNames.add(`${pascal}Errors`);
      responsesExpr = `${pascal}Responses & ${pascal}Errors`;
    }

    const { path, query, headers, body } = requestTypeExpression(op, pascal);
    methods.push(
      `  ${camel}(\n` +
        `    request: HandlerRequest<${path}, ${query}, ${headers}, ${body}>,\n` +
        '    context: RequestContext,\n' +
        `  ): Promise<HandlerResponse<${responsesExpr}>>;`,
    );
  }

  const readableImport = needsReadable ? "import type { Readable } from 'node:stream';\n" : '';
  const dataImportList = [...dataTypeNames].sort();
  const responseImportList = [...responseTypeNames].sort();
  const typesImport =
    dataImportList.length + responseImportList.length > 0
      ? `import type { ${[...dataImportList, ...responseImportList].join(', ')} } from './types.gen.js';\n`
      : '';

  return (
    HEADER +
    readableImport +
    "import type { HandlerRequest, HandlerResponse, RequestContext } from './server-adapter.js';\n" +
    typesImport +
    '\n' +
    'export interface Handlers {\n' +
    methods.join('\n\n') +
    '\n}\n'
  );
}
