const HEADER = '// Generated by Speckify. Do not edit by hand.\n';

/**
 * Generates `server.ts`: the small public surface a consumer imports from
 * `<package>/server` (`createServer`, `Handlers`, and the adapter's
 * supporting types), wiring the generated `Handlers` interface and route
 * table into the template's `createRequestListener`.
 */
export function generateServerEntrySource(): string {
  return (
    HEADER +
    "import { createRequestListener } from './server-adapter.js';\n" +
    "import type { ListenerOptions } from './server-adapter.js';\n" +
    "import type { Handlers } from './handlers.gen.js';\n" +
    "import { routes } from './routes.gen.js';\n" +
    '\n' +
    "export type { Handlers } from './handlers.gen.js';\n" +
    "export type { HandledResponse, HandlerRequest, HandlerResponse, ListenerOptions, RequestContext, RouteDefinition } from './server-adapter.js';\n" +
    "export { routes } from './routes.gen.js';\n" +
    '\n' +
    '/** Builds a node:http request listener dispatching to `handlers` per the generated route table. */\n' +
    'export function createServer(\n' +
    '  handlers: Handlers,\n' +
    '  options?: ListenerOptions,\n' +
    '): ReturnType<typeof createRequestListener> {\n' +
    '  return createRequestListener(handlers, routes, options);\n' +
    '}\n'
  );
}
