import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { importNameFor } from './naming.js';
import type { BuildPythonPackageInput } from './types.js';

function renderPyprojectToml(input: BuildPythonPackageInput, importName: string): string {
  const dependencies = ['httpx>=0.27', 'attrs>=23', 'pydantic>=2'];
  const lines = [
    '[build-system]',
    'requires = ["hatchling"]',
    'build-backend = "hatchling.build"',
    '',
    '[project]',
    `name = "${input.packageName}"`,
    `version = "${input.version}"`,
    'requires-python = ">=3.10"',
    `dependencies = ${JSON.stringify(dependencies)}`,
    '',
    '[project.optional-dependencies]',
    // fastapi is only pulled in for consumers that use the server submodule,
    // per the brief: a pure client install never needs a web framework.
    'server = ["fastapi>=0.110"]',
    '',
    '[tool.hatch.build.targets.wheel]',
    `packages = ["src/${importName}"]`,
    '',
    '[tool.speckify]',
    `version = "${input.version}"`,
    `speckify_version = "${input.speckifyVersion}"`,
    '',
  ];
  return lines.join('\n');
}

function renderReadme(input: BuildPythonPackageInput, importName: string): string {
  return [
    `# ${input.packageName}`,
    '',
    'Generated by Speckify from a bundled OpenAPI contract. Do not edit the generated',
    'modules by hand — regenerate from the contract instead.',
    '',
    '## Contents',
    '',
    `- \`${importName}.models\` — pydantic models generated from the contract's schemas.`,
    ...(input.client ? [`- \`${importName}.client\` — a generated HTTP client.`] : []),
    ...(input.server
      ? [
          `- \`${importName}.server\` — a \`Handlers\` protocol and \`create_router()\` for a FastAPI` +
            ' app implementing the contract (install the `server` extra).',
        ]
      : []),
    `- \`${importName}/openapi.json\` — the bundled contract this package was generated from.`,
    '',
  ].join('\n');
}

/**
 * Writes every non-generated part of the package: `pyproject.toml`, `README.md`,
 * `CHANGELOG.md`, the `py.typed` marker, and the bundled spec as package data.
 * `models.py`/`models/`, `client/` and `server/` are written by their own
 * generators into `src/<import_name>/` alongside these.
 */
export async function writeProjectFiles(
  input: BuildPythonPackageInput,
  projectDir: string,
): Promise<string> {
  const importName = importNameFor(input.packageName);
  const packageDir = join(projectDir, 'src', importName);
  await mkdir(packageDir, { recursive: true });

  await writeFile(
    join(projectDir, 'pyproject.toml'),
    renderPyprojectToml(input, importName),
    'utf8',
  );
  await writeFile(join(projectDir, 'README.md'), renderReadme(input, importName), 'utf8');
  await writeFile(join(projectDir, 'CHANGELOG.md'), input.changelog, 'utf8');
  await writeFile(join(packageDir, 'py.typed'), '', 'utf8');
  await writeFile(join(packageDir, 'openapi.json'), input.bundledSpec, 'utf8');
  // pyproject.toml's [tool.speckify] is not packaged into the built wheel's
  // METADATA, so the generating Speckify version is embedded here too, as
  // package data readable straight out of the wheel (record/pypi.ts reads
  // this back to compute each release's toolchain impact).
  await writeFile(
    join(packageDir, 'speckify.json'),
    `${JSON.stringify({ speckifyVersion: input.speckifyVersion })}\n`,
    'utf8',
  );
  await writeFile(join(packageDir, '__init__.py'), '', 'utf8');

  return packageDir;
}
