import { readFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { readAgentSkillTemplate } from './agent-skill-template.js';

const repoRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

describe('readAgentSkillTemplate', () => {
  it('reads the shipped template with the expected frontmatter and disclosure', async () => {
    const skill = await readAgentSkillTemplate();
    expect(skill).toContain('name: speckify');
    expect(skill).toContain('description:');
    expect(skill).toContain(
      'This skill was generated by Speckify; its text was written by an AI model',
    );
  });

  it('is found from where the built package will look for it (repoRoot/templates, a sibling of dist)', async () => {
    // `readAgentSkillTemplate` resolves `templates/agent-skill/SKILL.md`
    // two directories up from its own compiled location (`dist/init/`),
    // landing on a top-level `templates/` directory -- the same shape as
    // `data/` and `python/`, both listed in package.json's `files` next to
    // `dist`, rather than a path copied to live *inside* `dist/`. This
    // asserts that shape directly, so a future refactor that moves the
    // template under `dist/` (breaking the built package) fails here
    // rather than only in an end-to-end npm-pack install.
    const templatePath = path.join(repoRoot, 'templates', 'agent-skill', 'SKILL.md');
    await expect(stat(templatePath)).resolves.toBeDefined();
    const direct = await readFile(templatePath, 'utf8');
    const viaHelper = await readAgentSkillTemplate();
    expect(direct).toBe(viaHelper);
  });
});
