import { describe, expect, it } from 'vitest';

import { getConfigStringValue, resolveToolchainImpactBump } from './cli.js';
import type { SpeckifyConfig } from './config/index.js';
import type { RegistryRecordEntry } from './record/index.js';
import type { ToolchainImpactEntry } from './version/index.js';

const toolchainImpactEntries: ToolchainImpactEntry[] = [
  { speckifyVersion: '0.1.0', impact: 'none' },
  { speckifyVersion: '0.2.0', impact: 'major' },
];

describe('resolveToolchainImpactBump', () => {
  it('is none when the contract has never been published', () => {
    expect(resolveToolchainImpactBump(null, toolchainImpactEntries, '0.2.0')).toBe('none');
  });

  // The previous published state carries two independent version axes
  // -- the contract's own semver (`version`, e.g. "1.2.0") and the Speckify
  // toolchain version that generated it (`speckifyVersion`, e.g. "0.1.0").
  // Confusing the two means a contract sitting at a high semver (many spec
  // changes) but generated by an old, low Speckify version would report
  // `toolchainImpact` as if generated by "1.2.0" -- a version that appears
  // nowhere in toolchain-impact.json, so `gt(entry.speckifyVersion,
  // "1.2.0")` is false for every real entry and the bump silently comes
  // back `none`, hiding a real generator-level breaking change.
  it('uses speckifyVersion, never the contract version, to gate which toolchain releases count', () => {
    const previous: RegistryRecordEntry = {
      version: '1.2.0',
      bundledSpec: '{}',
      speckifyVersion: '0.1.0',
    };

    expect(resolveToolchainImpactBump(previous, toolchainImpactEntries, '0.2.0')).toBe('major');
  });

  it('fail-safes to the max impact when the previous package does not record its generating version', () => {
    const previous: RegistryRecordEntry = {
      version: '1.2.0',
      bundledSpec: '{}',
      speckifyVersion: null,
    };

    expect(resolveToolchainImpactBump(previous, toolchainImpactEntries, '0.2.0')).toBe('major');
  });
});

// The `config get` command exists so action.yml can read the caller's npm
// scope through parsed, validated config rather than grep-ing the YAML
// text -- a naive grep reads an inline comment
// ("owner: acme # trailing note") as part of the value. getConfigStringValue
// is the pure lookup that command wraps; src/e2e/built-cli.test.ts proves
// the actual `config get` subcommand end to end against the built CLI.
describe('getConfigStringValue', () => {
  const config: SpeckifyConfig = {
    contracts: [{ name: 'widgets', spec: './openapi.yaml' }],
    publish: { githubPackages: { owner: 'acme' } },
  };

  it('reads a nested string value by dotted path', () => {
    expect(getConfigStringValue(config, 'publish.githubPackages.owner')).toBe('acme');
  });

  it('returns undefined for a path that does not exist', () => {
    expect(getConfigStringValue(config, 'publish.somethingElse')).toBeUndefined();
  });

  it('returns undefined when a path segment resolves to a non-object before the end', () => {
    expect(getConfigStringValue(config, 'publish.githubPackages.owner.nested')).toBeUndefined();
  });

  it('returns undefined when the final value is not a string', () => {
    expect(getConfigStringValue(config, 'contracts')).toBeUndefined();
  });
});
