import { describe, expect, it } from 'vitest';

import { resolveToolchainImpactBump } from './cli.js';
import type { RegistryRecordEntry } from './record/index.js';
import type { ToolchainImpactEntry } from './version/index.js';

const toolchainImpactEntries: ToolchainImpactEntry[] = [
  { speckifyVersion: '0.1.0', impact: 'none' },
  { speckifyVersion: '0.2.0', impact: 'major' },
];

describe('resolveToolchainImpactBump', () => {
  it('is none when the contract has never been published', () => {
    expect(resolveToolchainImpactBump(null, toolchainImpactEntries, '0.2.0')).toBe('none');
  });

  // The previous published state carries two independent version axes
  // -- the contract's own semver (`version`, e.g. "1.2.0") and the Speckify
  // toolchain version that generated it (`speckifyVersion`, e.g. "0.1.0").
  // Confusing the two means a contract sitting at a high semver (many spec
  // changes) but generated by an old, low Speckify version would report
  // `toolchainImpact` as if generated by "1.2.0" -- a version that appears
  // nowhere in toolchain-impact.json, so `gt(entry.speckifyVersion,
  // "1.2.0")` is false for every real entry and the bump silently comes
  // back `none`, hiding a real generator-level breaking change.
  it('uses speckifyVersion, never the contract version, to gate which toolchain releases count', () => {
    const previous: RegistryRecordEntry = {
      version: '1.2.0',
      bundledSpec: '{}',
      speckifyVersion: '0.1.0',
    };

    expect(resolveToolchainImpactBump(previous, toolchainImpactEntries, '0.2.0')).toBe('major');
  });

  it('fail-safes to the max impact when the previous package does not record its generating version', () => {
    const previous: RegistryRecordEntry = {
      version: '1.2.0',
      bundledSpec: '{}',
      speckifyVersion: null,
    };

    expect(resolveToolchainImpactBump(previous, toolchainImpactEntries, '0.2.0')).toBe('major');
  });
});
